/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FishInfoRouteImport } from './routes/FishInfo'
import { Route as IndexRouteImport } from './routes/index'

const FishInfoRoute = FishInfoRouteImport.update({
  id: '/FishInfo',
  path: '/FishInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/FishInfo': typeof FishInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/FishInfo': typeof FishInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/FishInfo': typeof FishInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/FishInfo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/FishInfo'
  id: '__root__' | '/' | '/FishInfo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FishInfoRoute: typeof FishInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/FishInfo': {
      id: '/FishInfo'
      path: '/FishInfo'
      fullPath: '/FishInfo'
      preLoaderRoute: typeof FishInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FishInfoRoute: FishInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
